// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrf8Jjs7U3HzZFhLC-79xlfXzYcanVLY',
    appId: '1:134147406526:web:fc3b8e9d0f8b32a2d1bcef',
    messagingSenderId: '134147406526',
    projectId: 'litera-71460',
    authDomain: 'litera-71460.firebaseapp.com',
    storageBucket: 'litera-71460.firebasestorage.app',
    measurementId: 'G-0488SV0393',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrZqZboWZ96wpbZwttcglu4TwH4XYYMo',
    appId: '1:134147406526:android:55650b768ba90250d1bcef',
    messagingSenderId: '134147406526',
    projectId: 'litera-71460',
    storageBucket: 'litera-71460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUX3QxvWA3blIZkAI0fOFM9MjmAKJ1IM8',
    appId: '1:134147406526:ios:8ee5567e634b64cad1bcef',
    messagingSenderId: '134147406526',
    projectId: 'litera-71460',
    storageBucket: 'litera-71460.firebasestorage.app',
    iosBundleId: 'com.example.litera',
  );
}
