// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr_hpc4uTG9Q_OS4qsuiEWgVye3TmxDEs',
    appId: '1:886996875210:web:88422c1358e7bdf73c0133',
    messagingSenderId: '886996875210',
    projectId: 'codexia-c3435',
    authDomain: 'codexia-c3435.firebaseapp.com',
    storageBucket: 'codexia-c3435.firebasestorage.app',
    measurementId: 'G-7B01DF5QMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMlXUN6PeFj08IfGWse8MIGDcrcyMx9Q',
    appId: '1:886996875210:android:5523cf0274fa2e253c0133',
    messagingSenderId: '886996875210',
    projectId: 'codexia-c3435',
    storageBucket: 'codexia-c3435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0Fd5io1xiIXVKOP_rj_5fiqxFARA35s',
    appId: '1:886996875210:ios:0f920d5c128bfac63c0133',
    messagingSenderId: '886996875210',
    projectId: 'codexia-c3435',
    storageBucket: 'codexia-c3435.firebasestorage.app',
    iosBundleId: 'com.example.codexia',
  );
}
